services:
  ts-node-setup:
    image: cristutz84/ts-node-image
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    container_name: ts-node-setup
    command: npm run dev
    ports:
      - 4001:80
    working_dir: /ts-node-setup
    volumes:
      - ./:/ts-node-setup
    networks:
      - nodemongo
    environment:
      DB_NAME: mongodb://db-container

networks:
  nodemongo:
    name: nodemongo
    external: true
