name: Publish

on:
  push:
    branches:
      - "*"
      - "*/*"
      - "!release"
      - "!main"
  workflow_dispatch:

jobs:
  setup:
    uses: ./.github/workflows/setup.yml

  lint:
    needs: setup
    uses: ./.github/workflows/lint.yml

  test:
    needs: lint
    uses: ./.github/workflows/test.yml

  build:
    needs: test
    uses: ./.github/workflows/build.yml    

  publish:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Publish App
        run: echo "Publishing ...."