name: testing stuff

on:
  push:
    branches:
      - "*"
      - "*/*"
      - "!release"
      - "!main"
  workflow_dispatch:
  workflow_call:

jobs:
  setup:
    uses: ./.github/workflows/setup.yml

  lint:
    needs: setup
    uses: ./.github/workflows/lint.yml

  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Cache node_modules
        id: cache_all
        uses: actions/cache@v3
        with:
          path: |
            node_modules
          key: install-id_${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: steps.cache_all.outputs.cache-hit != 'true'
        run: npm ci
      - name: Cache Jest dependencies
        id: cache_jest_dependencies
        uses: actions/cache@v3
        with:
          path: /tmp/jest_rt
          key: jest_cache_id_${{ hashFiles('**/package-lock.json') }}
      - name: Run tests
        run: npm run test:ci -- --maxWorkers=4

  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
      # - name: Checkout
      #   uses: actions/checkout@v3
      # - name: Setup Node
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: 18
      # - name: Cache node_modules
      #   id: cache_all
      #   uses: actions/cache@v3
      #   with:
      #     path: |
      #       ~/.npm
      #       node_modules
      #     key: cache-id_${{ hashFiles('**/package-lock.json') }}
      # - name: Install dependencies
      #   if: steps.cache_all.outputs.cache-hit != 'true'
      #   run: npm ci
      - name: Build resources
        run: echo "building...."

  # publish:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       node: ["16.17.1"]

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #     - name: Configure Node.js ${{ matrix.node-version }} & Npm
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: ${{ matrix.version }}
  #         registry-url: https://npm.pkg.github.com/mavrck-inc
  #         cache: 'npm'
  #         cache-dependency-path: '**/package-lock.json'
  #     - name: Cache node modules
  #       uses: actions/cache@v3
  #       env:
  #         cache-name: cache-node-modules
  #       with:
  #         # npm cache files are stored in `~/.npm` on Linux/macOS
  #         path: ~/.npm
  #         key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
  #         restore-keys: |
  #           ${{ runner.os }}-build-${{ env.cache-name }}-
  #           ${{ runner.os }}-build-
  #           ${{ runner.os }}-
  #     - name: Install dependencies
  #       run: npm ci
  #     - name: Build resources
  #       run: npm run build --if-present
  #     - name: Publish
  #       env:
  #         GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
  #       run: npx semantic-release
